artifact_uri: file:///C:/Users/pesso/Documents/DevProjects/GitHubRepositories/ml_models/infnet_04_ml_engineering_pd/mlruns/159606787888690177/29deb0e5c741469fbe707326fd01fab8/artifacts
end_time: 1744496208129
entry_point_name: ''
experiment_id: '159606787888690177'
lifecycle_stage: active
run_id: 29deb0e5c741469fbe707326fd01fab8
run_name: trainer
run_uuid: 29deb0e5c741469fbe707326fd01fab8
source_name: ''
source_type: 4
source_version: ''
start_time: 1744496207466
status: 4
tags: []
user_id: pesso
