artifact_uri: file:///C:/Users/pesso/Documents/DevProjects/GitHubRepositories/ml_models/infnet_04_ml_engineering_pd/mlruns/159606787888690177/18f215ab042d487cb31c1ccc69ecc8a7/artifacts
end_time: 1744491554816
entry_point_name: ''
experiment_id: '159606787888690177'
lifecycle_stage: active
run_id: 18f215ab042d487cb31c1ccc69ecc8a7
run_name: amusing-hen-70
run_uuid: 18f215ab042d487cb31c1ccc69ecc8a7
source_name: ''
source_type: 4
source_version: ''
start_time: 1744491554423
status: 3
tags: []
user_id: pesso
