artifact_uri: file:///C:/Users/pesso/Documents/DevProjects/GitHubRepositories/ml_models/infnet_04_ml_engineering_pd/mlruns/159606787888690177/58e385ebceef4f2e94cb34fa9a1ad50f/artifacts
end_time: 1744555983629
entry_point_name: ''
experiment_id: '159606787888690177'
lifecycle_stage: active
run_id: 58e385ebceef4f2e94cb34fa9a1ad50f
run_name: process_prod_data_node
run_uuid: 58e385ebceef4f2e94cb34fa9a1ad50f
source_name: ''
source_type: 4
source_version: ''
start_time: 1744555983497
status: 3
tags: []
user_id: pesso
