artifact_uri: file:///C:/Users/pesso/Documents/DevProjects/GitHubRepositories/ml_models/infnet_04_ml_engineering_pd/mlruns/159606787888690177/67bda7f343f74ee9a6a0229e47221d36/artifacts
end_time: 1744489849439
entry_point_name: ''
experiment_id: '159606787888690177'
lifecycle_stage: active
run_id: 67bda7f343f74ee9a6a0229e47221d36
run_name: process_prod_data_node
run_uuid: 67bda7f343f74ee9a6a0229e47221d36
source_name: ''
source_type: 4
source_version: ''
start_time: 1744489849321
status: 3
tags: []
user_id: pesso
