api_key:
  key: "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"


model:
  name: "llama3-70b-8192" 
  temperature: 0.3
  frequency_penalty: 0.0
  presence_penalty: 0.0
  max_tokens: 1024
  n: 1
  seed: 42