artifact_uri: file:///C:/Users/pesso/Documents/DevProjects/GitHubRepositories/ml_models/infnet_04_ml_engineering_pd/mlruns/159606787888690177/23d8b8486f4c4edb9b921b173b5b0a1c/artifacts
end_time: 1744555077771
entry_point_name: ''
experiment_id: '159606787888690177'
lifecycle_stage: active
run_id: 23d8b8486f4c4edb9b921b173b5b0a1c
run_name: inference
run_uuid: 23d8b8486f4c4edb9b921b173b5b0a1c
source_name: ''
source_type: 4
source_version: ''
start_time: 1744555077551
status: 4
tags: []
user_id: pesso
