artifact_uri: file:///C:/Users/pesso/Documents/DevProjects/GitHubRepositories/ml_models/infnet_04_ml_engineering_pd/mlruns/159606787888690177/38a8f27b46b94af8a867bdfff09524a4/artifacts
end_time: 1744545657349
entry_point_name: ''
experiment_id: '159606787888690177'
lifecycle_stage: active
run_id: 38a8f27b46b94af8a867bdfff09524a4
run_name: inference
run_uuid: 38a8f27b46b94af8a867bdfff09524a4
source_name: ''
source_type: 4
source_version: ''
start_time: 1744545654066
status: 3
tags: []
user_id: pesso
