artifact_uri: file:///C:/Users/pesso/Documents/DevProjects/GitHubRepositories/ml_models/infnet_04_ml_engineering_pd/mlruns/159606787888690177/44e9b6e867d442e1be9bcff8e3abf002/artifacts
end_time: 1744496740200
entry_point_name: ''
experiment_id: '159606787888690177'
lifecycle_stage: active
run_id: 44e9b6e867d442e1be9bcff8e3abf002
run_name: painted-croc-108
run_uuid: 44e9b6e867d442e1be9bcff8e3abf002
source_name: ''
source_type: 4
source_version: ''
start_time: 1744496739928
status: 3
tags: []
user_id: pesso
