artifact_uri: file:///C:/Users/pesso/Documents/DevProjects/GitHubRepositories/ml_models/infnet_04_ml_engineering_pd/mlruns/159606787888690177/013e3be8b6464b30abd23f11d5d9f439/artifacts
end_time: 1744556038485
entry_point_name: ''
experiment_id: '159606787888690177'
lifecycle_stage: active
run_id: 013e3be8b6464b30abd23f11d5d9f439
run_name: extract_prod_features_node
run_uuid: 013e3be8b6464b30abd23f11d5d9f439
source_name: ''
source_type: 4
source_version: ''
start_time: 1744556038268
status: 3
tags: []
user_id: pesso
